### ISSUE TITLE
Creating models from the search space 

### ISSUE THREAD

**Issue by DanielHesslow** [automl/nasbench301#3]
Could you release the code for generating the models based on a ConfigSpace Instance of the search space so that it is possible to retrain them yourself? 

While it is probably possible to get something close to what you have used based on the code in the original DARTS repo I'd much rather get identical models if possible. 

Thanks

**Comment by IHIaadj** [comment]
Hi, 

Is the dataset released on OGB or not yet, couldn't find it. 

Thanks

**Comment by arberzela** [comment]
Hi,

This was pretty late but I just uploaded the training scripts at nasbench301/data_generation/. Since we have been using an older version of Auto-PyTorch for that I uploaded that in a new branch at the Auto-PyTorch repository and updated the requirements.txt file here to automatically install that version. I updated the README.md with the necessary instructions to run the architecture training.

Cheers,
Arber

**Comment by akhauriyash** [comment]
Hello,

Thanks for putting the training scripts.
However, I still do not understand how I can initialize a model from a config.
For instance, how do I get a PyTorch model from the following config:

```
config = {'NetworkSelectorDatasetInfo:darts:edge_normal_0': 'max_pool_3x3', 'NetworkSelectorDatasetInfo:darts:edge_normal_1': 'dil_conv_3x3', 'NetworkSelectorDatasetInfo:darts:edge_normal_3': 'skip_connect', 'NetworkSelectorDatasetInfo:darts:edge_normal_4': 'skip_connect', 'NetworkSelectorDatasetInfo:darts:inputs_node_normal_3': '1_2', 'NetworkSelectorDatasetInfo:darts:edge_normal_5': 'sep_conv_5x5', 'NetworkSelectorDatasetInfo:darts:edge_normal_6': 'dil_conv_3x3', 'NetworkSelectorDatasetInfo:darts:inputs_node_normal_4': '0_1', 'NetworkSelectorDatasetInfo:darts:edge_normal_10': 'avg_pool_3x3', 'NetworkSelectorDatasetInfo:darts:edge_normal_9': 'sep_conv_5x5', 'NetworkSelectorDatasetInfo:darts:inputs_node_normal_5': '0_1', 'NetworkSelectorDatasetInfo:darts:edge_reduce_0': 'max_pool_3x3', 'NetworkSelectorDatasetInfo:darts:edge_reduce_1': 'dil_conv_3x3', 'NetworkSelectorDatasetInfo:darts:edge_reduce_3': 'skip_connect', 'NetworkSelectorDatasetInfo:darts:edge_reduce_4': 'skip_connect', 'NetworkSelectorDatasetInfo:darts:inputs_node_reduce_3': '1_2', 'NetworkSelectorDatasetInfo:darts:edge_reduce_5': 'sep_conv_5x5', 'NetworkSelectorDatasetInfo:darts:edge_reduce_6': 'dil_conv_3x3', 'NetworkSelectorDatasetInfo:darts:inputs_node_reduce_4': '0_1', 'NetworkSelectorDatasetInfo:darts:edge_reduce_10': 'avg_pool_3x3', 'NetworkSelectorDatasetInfo:darts:edge_reduce_9': 'sep_conv_5x5', 'NetworkSelectorDatasetInfo:darts:inputs_node_reduce_5': '0_1', 'NetworkSelectorDatasetInfo:network': 'darts'}
```
